"""empty message

Revision ID: 07ea35db7af3
Revises: 9882312b929f
Create Date: 2023-11-28 09:01:06.064241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '07ea35db7af3'
down_revision: Union[str, None] = '9882312b929f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'image_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('image_content', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
