"""empty message

Revision ID: 11f056b33881
Revises: 13438a7b6b4d
Create Date: 2023-11-19 21:01:55.074271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '11f056b33881'
down_revision: Union[str, None] = '13438a7b6b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unfollows')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unfollows',
    sa.Column('followed_username', sa.VARCHAR(), nullable=False),
    sa.Column('follower_username', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('followed_username', 'follower_username')
    )
    # ### end Alembic commands ###
