"""empty message

Revision ID: 4f617f6a7d74
Revises: 0d2c51716dc5
Create Date: 2023-11-23 11:46:04.110437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4f617f6a7d74'
down_revision: Union[str, None] = '0d2c51716dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'map_html')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('map_html', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
