"""empty message

Revision ID: 5fa76a078714
Revises: 6a42b1ae78e2
Create Date: 2023-11-25 16:36:46.923811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5fa76a078714'
down_revision: Union[str, None] = '6a42b1ae78e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt', sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpt', 'created_at')
    # ### end Alembic commands ###
